export const ShopActionTypes = {
    //UPDATE_COLLECTIONS : 'UPDATE_COLLECTIONS' replaced by fetch collections start,success
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS:'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE:'FETCH_COLLECTIONS_FAILURE'
}

export default ShopActionTypes